### ISSUE TITLE
Letsencrypt needs  -verify_other

### ISSUE THREAD

**Issue by HLeithner** [pierky/haproxy-ocsp-stapling-updater#8]
While trying to use this script with Lesencrypt I didn't successfully verify the certificate.

After adding ```-verify_other $TMP/chain.php``` to the ocsp command, I get a valid ocsp stable.

**Comment by pierky** [comment]
Hello @HLeithner, thanks for your feedback.

Adding `-verify_other $TMP/chain.pem` to the `ocsp` call inside the script is the same as passing the `--VAfile -` argument to `hapos-upd`.

Do you think this is good enough to solve your issue?

**Comment by pierky** [comment]
Hello @HLeithner,

I didn't hear back from you about this issue, did what I suggested work for you? I tentatively close it but please feel free to add further comments if needed.

**Comment by HLeithner** [comment]
Oh sorry, I tested it and it works fine, maybe a note for letsencrypt users would be useful ;)
